export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const AUTH_SET_LOADING = "AUTH_SET_LOADING";
export const AUTH_NOTIFICATION = "AUTH_NOTIFICATION";

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const FETCH_COURSES = 'FETCH_COURSES';

export const FETCH_CALCULATORS = 'FETCH_CALCULATORS';

export const FETCH_TESTS = 'FETCH_TESTS';